### Part 1 — Smart Array Factory

In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        return np.full(shape, value)

    elif mode == "identity":
        return np.eye(shape)

    else:
        raise ValueError("invalid mode")

In [2]:
print(array_factory("zeros", (2, 3)))
print(array_factory("ones", (2, 3)))
print(array_factory("full", (2, 3), 5))
print(array_factory("identity", 3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Part 2 — secure_reshape_and_stack

In [3]:
import numpy as np
def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        # Rule: Change the shape of arr1 to new_shape
        # Common usage: turning a vector (1D) into a matrix (2D) by using reshape function
        reshaped_arr1 = arr1.reshape(new_shape)
        # Rule: Vertical stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

In [4]:
data1 = [1, 2, 3, 4]
data2 = [[5, 6], [7, 8]]

result = secure_reshape_and_stack(data1, data2, (2, 2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
